import React from "react";
import "./Education.css";
export const Education = () => {
  return (
    <div className="education-container">
      <h3>SKILLS</h3>
      <p>
        HTML- CSS NODE.JS- JAVASCRIPT- EXPRESS- MYSQL BD- MONGO DB- PHYTON- APIS-
        REACT- SCRUM- GITHUB- TRELLO- FIGMA.
      </p>
      <h3>EDUCACION</h3>
      <p> ISPC INSTITUTO SUPERIOR POLITECNICO CÓRDOBA</p>
      <p>TEC SUP EN TELECOMUNICACIONES - ACTUALMENTE</p>
      <p>TEC SUP EN TECNOLOGÍAS 4.0 MARZO 2022 - ACTUALMENTE</p>
      <p>DIGITAL HOUSE</p>
      <p>PROGRAMADOR WEB FULL STACK</p>
      <p>PERIODO: JUNIO DE 2021 | DICIEMBRE DE 2021 </p>
      <p>SECUNDARIA CENS 451 SAN ISIDRO </p>
      <p>TITULO ACADEMICO:BACHILLER CON ORIENTACION EN POLITICAS PUBLICAS </p>
      PERIODO : AGOSTO DE 2018| AGOSTO DE 2020
      <p>POLO TECNOLOGICO TIGRE </p>
      TITULO ACADEMICO: TECNICO EN INSTALACION DE REDES INFORMTICAS PERIODO:
      MARZO DE 2019 | SEPTIEMBRE DE 2019
    </div>
  );
};
export default Education;
